<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.journeybuilder/xml/schema/CRM/Journeybuilder/JourneyAnalytics.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0544ad86b5f024d522f476d9e11e3f92)
 */
use CRM_Journeybuilder_ExtensionUtil as E;

/**
 * Database access object for the JourneyAnalytics entity.
 */
class CRM_Journeybuilder_DAO_JourneyAnalytics extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_journey_analytics';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique JourneyAnalytics ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to journey
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $journey_id;

  /**
   * FK to Steps
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $step_id;

  /**
   * FK to Contact
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Event Type
   *
   * @var string|null
   *   (SQL type: varchar(0))
   *   Note that values will be retrieved from the database as a string.
   */
  public $event_type;

  /**
   * Event Data.
   *
   * @var string|null
   *   (SQL type: longtext)
   *   Note that values will be retrieved from the database as a string.
   */
  public $event_data;

  /**
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $event_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_journey_analytics';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Journey Analyticses') : E::ts('Journey Analytics');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique JourneyAnalytics ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_journey_analytics.id',
          'table_name' => 'civicrm_journey_analytics',
          'entity' => 'JourneyAnalytics',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyAnalytics',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'journey_id' => [
          'name' => 'journey_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Journey ID'),
          'description' => E::ts('FK to journey'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_journey_analytics.journey_id',
          'table_name' => 'civicrm_journey_analytics',
          'entity' => 'JourneyAnalytics',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyAnalytics',
          'localizable' => 0,
          'FKClassName' => 'CRM_Journeybuilder_DAO_JourneyCampaign',
          'add' => NULL,
        ],
        'step_id' => [
          'name' => 'step_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Step ID'),
          'description' => E::ts('FK to Steps'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_journey_analytics.step_id',
          'table_name' => 'civicrm_journey_analytics',
          'entity' => 'JourneyAnalytics',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyAnalytics',
          'localizable' => 0,
          'FKClassName' => 'CRM_Journeybuilder_DAO_JourneyStep',
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact'),
          'description' => E::ts('FK to Contact'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_journey_analytics.contact_id',
          'table_name' => 'civicrm_journey_analytics',
          'entity' => 'JourneyAnalytics',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyAnalytics',
          'localizable' => 0,
          'add' => NULL,
        ],
        'event_type' => [
          'name' => 'event_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Event Type'),
          'description' => E::ts('Event Type'),
          'maxlength' => 0,
          'size' => CRM_Utils_Type::TWO,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_journey_analytics.event_type',
          'table_name' => 'civicrm_journey_analytics',
          'entity' => 'JourneyAnalytics',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyAnalytics',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Journeybuilder_BAO_JourneyAnalytics::eventType',
          ],
          'add' => '1.0',
        ],
        'event_data' => [
          'name' => 'event_data',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Event Data'),
          'description' => E::ts('Event Data.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_journey_analytics.event_data',
          'export' => TRUE,
          'table_name' => 'civicrm_journey_analytics',
          'entity' => 'JourneyAnalytics',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyAnalytics',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '1.0',
        ],
        'event_date' => [
          'name' => 'event_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Event Date'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_journey_analytics.event_date',
          'headerPattern' => '/Event(.?date)?/i',
          'dataPattern' => '/^\d{4}-?\d{2}-?\d{2} ?(\d{2}:?\d{2}:?(\d{2})?)?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_journey_analytics',
          'entity' => 'JourneyAnalytics',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyAnalytics',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'journey_analytics', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'journey_analytics', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
