<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.journeybuilder/xml/schema/CRM/Journeybuilder/JourneyStep.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:3ce831035d9d0e108115b5e4fe423c71)
 */
use CRM_Journeybuilder_ExtensionUtil as E;

/**
 * Database access object for the JourneyStep entity.
 */
class CRM_Journeybuilder_DAO_JourneyStep extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_journey_steps';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique JourneyStep ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to journey
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $journey_id;

  /**
   * step type
   *
   * @var string|null
   *   (SQL type: varchar(0))
   *   Note that values will be retrieved from the database as a string.
   */
  public $step_type;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * Configuration.
   *
   * @var string|null
   *   (SQL type: longtext)
   *   Note that values will be retrieved from the database as a string.
   */
  public $configuration;

  /**
   * position x
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $position_x;

  /**
   * Position Y
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $position_y;

  /**
   * Sort Order
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sort_order;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_journey_steps';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Journey Steps') : E::ts('Journey Step');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique JourneyStep ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_journey_steps.id',
          'table_name' => 'civicrm_journey_steps',
          'entity' => 'JourneyStep',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyStep',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'journey_id' => [
          'name' => 'journey_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Journey'),
          'description' => E::ts('FK to journey'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_journey_steps.journey_id',
          'table_name' => 'civicrm_journey_steps',
          'entity' => 'JourneyStep',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyStep',
          'localizable' => 0,
          'FKClassName' => 'CRM_Journeybuilder_DAO_JourneyCampaign',
          'add' => NULL,
        ],
        'step_type' => [
          'name' => 'step_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Step Type'),
          'description' => E::ts('step type'),
          'maxlength' => 0,
          'size' => CRM_Utils_Type::TWO,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_journey_steps.step_type',
          'table_name' => 'civicrm_journey_steps',
          'entity' => 'JourneyStep',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyStep',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Journeybuilder_BAO_JourneyStep::stepsType',
          ],
          'add' => '1.0',
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Step Name'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_journey_steps.name',
          'export' => TRUE,
          'table_name' => 'civicrm_journey_steps',
          'entity' => 'JourneyStep',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyStep',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '1.0',
        ],
        'configuration' => [
          'name' => 'configuration',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Configuration'),
          'description' => E::ts('Configuration.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_journey_steps.configuration',
          'export' => TRUE,
          'table_name' => 'civicrm_journey_steps',
          'entity' => 'JourneyStep',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyStep',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '1.0',
        ],
        'position_x' => [
          'name' => 'position_x',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Position X'),
          'description' => E::ts('position x'),
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_journey_steps.position_x',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_journey_steps',
          'entity' => 'JourneyStep',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyStep',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("Position X"),
          ],
          'add' => NULL,
        ],
        'position_y' => [
          'name' => 'position_y',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Position Y'),
          'description' => E::ts('Position Y'),
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_journey_steps.position_y',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_journey_steps',
          'entity' => 'JourneyStep',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyStep',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("Position Y"),
          ],
          'add' => NULL,
        ],
        'sort_order' => [
          'name' => 'sort_order',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Sort Order'),
          'description' => E::ts('Sort Order'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_journey_steps.sort_order',
          'table_name' => 'civicrm_journey_steps',
          'entity' => 'JourneyStep',
          'bao' => 'CRM_Journeybuilder_DAO_JourneyStep',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("Sort Order"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'journey_steps', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'journey_steps', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'idx_step_type' => [
        'name' => 'idx_step_type',
        'field' => [
          0 => 'step_type',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_journey_steps::0::step_type',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
